version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" 
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "cargo"
    directory: "/fen_parser/"
    schedule:
      interval: "monthly"
