model:
  L1: 256

scaling:
  lambda_: 1.0
  nnue_2_score: 400
  cp_scaling: 312.93

training:
  batch_size: 8192
  workers: 8
  device: cuda
  training_dir: training
  testing_dir: testing
  save_dir: nets

#load: nets/2025-05-06T06-58-00/model_checkpoint_76.pth
