model:
  L1: 512
  N_BUCKETS: 8

scaling:
  lambda_: 1.0
  nnue_2_score: 400
  cp_scaling: 284.61

training:
  batch_size: 8192
  workers: 8
  device: cuda
  training_dir: training
  testing_dir: testing
  save_dir: nets
  epochs: 60
  wdl_epochs: 10
  max_lr: 1.0e-3
  warmup_frac: 0.05

#load: nets/2026-07-02T17-49-37/model_checkpoint_15.pth
