[package]
name = "fen-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fen_parser"

crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.23.5"
features = ["extension-module"]